# Dependencies
plugins: [jekyll-paginate]

# Features
excerpt_separator: <!--more-->
categories: "economics|data|maths|programming|machine-learning"

# Permalinks
permalink: /:year/:month/:day/:title/

# Setup
title: Yuchao Fan
tagline: "always learning"
description: "always learning"
url: ""
baseurl:
imageurl: "/assets/images/"

author:
  name: "Yuchao Fan"

# Custom vars
future: TRUE
version: 2.1.0

github:
  repo: https://github.com/yuchaofan13

social:
  linkedin: https://www.linkedin.com/in/yuchaofan/

# Structure
paginate: 10

collections:
  notes:
    output: true
    permalink: /notes/:path/
